---
title: "Lesson 1: Gapminder"
date: "November 1, 2024"
author: "Brian Calhoon"
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
    toc: true
editor: visual
filters: 
  - webr
theme:
  -prep/styles.css
---

# Install and load packages

```{r eval = FALSE}
source(here::here("prep/prep.R"))
```

```{r eval = FALSE}
# install.packages(c("tidyverse", "gapminder"))

#load the libraries so you can use them
library(tidyverse)
library(gapminder)


```

# View the data

```{r}
#look at the gapminder dataset
gapminder

#make gapminder an object
df <- gapminder

#read variable names
names(df)
```

# Make a plot

```{r}
#make a plot
ggplot(data = df) +
  geom_point(aes(x = gdpPercap, y = lifeExp, color = continent)
             , alpha = .4) 

#make the plot an object
plot <- ggplot(data = df) +
  geom_point(aes(x = gdpPercap, y = lifeExp, color =  continent)
             , alpha = .4) 
```

```{r}
#use the object to add more things to the plot
plot +  
  
  #rescale data
  scale_x_log10() + 
  
  #add a smoothing line
  geom_smooth(aes(x = gdpPercap, y = lifeExp))
```

## Play around with customizing the plot

Now it's your turn practice! Below is a fully functioning code editor. Use the code above to start, and then try changing the variables or changing the type of chart from a scatter plot (`geom_point()`) to a line graph (`geom_line()`) or a bar graph (`geom_col()` or `geom_bar()`). 
```{webr-r}
library(ggplot2)
library(gapminder)

df <- gapminder

ggplot(df) +
  geom_point(aes(x = pop, y = lifeExp, color = continent)
             , alpha = .6)

```
